import { Manrope } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  display: "swap",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Banking Technology & Digital Financial Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.variable}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}